const STORAGE_KEY = 'pgmate-data-v1';
const categories = ['Rent', 'Food/Mess', 'Transport', 'Electricity', 'Wi-Fi/Mobile', 'Personal Care', 'Shopping', 'Entertainment', 'Study/Work', 'Other'];
const categoryIcons = { Rent: '⌂', 'Food/Mess': '◌', Transport: '↗', Electricity: 'ϟ', 'Wi-Fi/Mobile': '⌁', 'Personal Care': '✦', Shopping: '□', Entertainment: '♪', 'Study/Work': '✎', Other: '•' };
const currentMonth = new Date().toISOString().slice(0, 7);
const todayISO = new Date().toISOString().slice(0, 10);
let editingId = null;
let state = loadState();

function loadState() {
    const fallback = { income: 25000, goal: 5000, expenses: [], rent: { amount: 0, dueDate: '', paid: false }, split: { bill: 0, roommates: 1, yourShare: 0 } };
    try { return { ...fallback, ...JSON.parse(localStorage.getItem(STORAGE_KEY)) }; } catch { return fallback; }
}
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function money(value) { return `₹${Math.max(0, Number(value) || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`; }
function monthExpenses(month = currentMonth) { return state.expenses.filter(item => item.date?.slice(0, 7) === month); }
function sum(items) { return items.reduce((total, item) => total + Number(item.amount || 0), 0); }
function daysInMonth(month = currentMonth) { const [year, monthNumber] = month.split('-').map(Number); return new Date(year, monthNumber, 0).getDate(); }
function remainingDays() { const today = new Date(); return Math.max(1, daysInMonth(currentMonth) - today.getDate() + 1); }
function formatDate(date) { return date ? new Date(`${date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'; }
function currentMetrics() {
    const expenses = monthExpenses();
    const total = sum(expenses);
    const savings = Number(state.income || 0) - total;
    const remaining = Number(state.income || 0) - Number(state.goal || 0) - total;
    return { expenses, total, savings, remaining, daily: Math.max(0, remaining / remainingDays()) };
}
function categoryTotals(items = monthExpenses()) { return categories.map(category => ({ category, total: sum(items.filter(item => item.category === category)) })).filter(item => item.total > 0).sort((a, b) => b.total - a.total); }
function populateCategories() { const select = document.querySelector('#expense-category'); const filter = document.querySelector('#category-filter'); select.innerHTML = categories.map(category => `<option value="${category}">${category}</option>`).join(''); filter.innerHTML = `<option value="all">All categories</option>${categories.map(category => `<option value="${category}">${category}</option>`).join('')}`; }
function renderStats() {
    const metrics = currentMetrics();
    document.querySelector('#stat-income').textContent = money(state.income);
    document.querySelector('#stat-expenses').textContent = money(metrics.total);
    document.querySelector('#stat-savings').textContent = money(metrics.savings);
    document.querySelector('#stat-goal').textContent = money(state.goal);
    document.querySelector('#stat-daily').textContent = money(metrics.daily);
    document.querySelector('#stat-remaining').textContent = money(metrics.remaining);
    document.querySelector('#expense-meta').textContent = `${metrics.expenses.length} transaction${metrics.expenses.length === 1 ? '' : 's'} this month`;
    document.querySelector('#goal-meta').textContent = state.goal ? `${Math.round(Math.min(100, (metrics.savings / state.goal) * 100))}% of goal reached` : 'Set your target below';
    document.querySelector('#days-meta').textContent = `${remainingDays()} days remaining`;
    document.querySelector('#income-input').value = state.income || '';
    document.querySelector('#goal-input').value = state.goal || '';
    const alertTitle = document.querySelector('#alert-title'); const alertCopy = document.querySelector('#alert-copy');
    const budget = Number(state.income) - Number(state.goal);
    if (metrics.remaining < 0) { alertTitle.textContent = '⚠️ You\'re spending faster than your monthly budget.'; alertCopy.textContent = `${money(Math.abs(metrics.remaining))} over your safe spendable amount.`; }
    else if (state.goal > 0 && metrics.savings < state.goal) { alertTitle.textContent = '💡 Reduce unnecessary spending to stay on track with your saving goal.'; alertCopy.textContent = `${money(state.goal - Math.max(0, metrics.savings))} more savings needed at this pace.`; }
    else { alertTitle.textContent = 'You\'re on track with your budget! 🎉'; alertCopy.textContent = budget > 0 ? `${money(metrics.remaining)} remains available after your saving goal.` : 'A clear view of your spending starts here.'; }
}
function renderCategoryBars() {
    const items = categoryTotals(); const max = items[0]?.total || 1; const visible = items.slice(0, 5);
    document.querySelector('#category-bars').innerHTML = visible.length ? visible.map(item => `<div class="bar-row"><span class="bar-label">${item.category}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(item.total / max * 100)}%"></div></div><span class="bar-value">${money(item.total)}</span></div>`).join('') : '<div class="empty-mini">Your category breakdown will appear here.</div>';
}
function renderTable() {
    const search = document.querySelector('#search-input').value.toLowerCase(); const category = document.querySelector('#category-filter').value; const date = document.querySelector('#date-filter').value;
    const filtered = state.expenses.filter(item => (!search || `${item.description} ${item.category}`.toLowerCase().includes(search)) && (category === 'all' || item.category === category) && (!date || item.date?.slice(0, 7) === date)).sort((a, b) => b.date.localeCompare(a.date));
    const body = document.querySelector('#expense-table-body'); const empty = document.querySelector('#expense-empty');
    body.innerHTML = filtered.map(item => `<tr><td><strong>${escapeHTML(item.description)}</strong></td><td><span class="category-pill">${item.category}</span></td><td>${formatDate(item.date)}</td><td class="align-right"><strong>${money(item.amount)}</strong></td><td><div class="row-actions"><button class="icon-button edit-expense" data-id="${item.id}" aria-label="Edit ${escapeHTML(item.description)}">✎</button><button class="icon-button delete-expense" data-id="${item.id}" aria-label="Delete ${escapeHTML(item.description)}">⌫</button></div></td></tr>`).join('');
    empty.classList.toggle('hidden', filtered.length > 0); body.closest('table').style.display = filtered.length ? 'table' : 'none';
}
function renderBudget() {
    const m = currentMetrics(); const available = Math.max(0, Number(state.income) - Number(state.goal)); const used = Math.min(available, m.total); const percent = available ? used / available * 100 : 0;
    document.querySelector('#budget-available').textContent = money(available); document.querySelector('#budget-progress').style.width = `${percent}%`; document.querySelector('#budget-used-label').textContent = `${money(m.total)} used`; document.querySelector('#budget-total-label').textContent = `of ${money(available)}`;
    document.querySelector('#breakdown-income').textContent = money(state.income); document.querySelector('#breakdown-goal').textContent = money(state.goal); document.querySelector('#breakdown-expenses').textContent = money(m.total); document.querySelector('#breakdown-remaining').textContent = money(m.remaining);
}
function renderRent() { const rent = state.rent || {}; document.querySelector('#rent-input').value = rent.amount || ''; document.querySelector('#rent-due-input').value = rent.dueDate || ''; document.querySelector('#rent-paid-input').checked = Boolean(rent.paid); document.querySelector('#rent-amount').textContent = money(rent.amount); const status = document.querySelector('#rent-status'); status.innerHTML = `<span class="status-pip ${rent.paid ? 'paid' : 'unpaid'}"></span><strong>${rent.amount ? (rent.paid ? 'Paid' : 'Unpaid') : 'Not set'}</strong>`; document.querySelector('#rent-due-label').textContent = rent.dueDate ? `Due on ${formatDate(rent.dueDate)}${rent.paid ? ' · Nicely done.' : ' · Keep it on your radar.'}` : 'Add your rent details to see the due date.'; }
function renderSplit() { const split = state.split || {}; const share = split.roommates > 0 ? Number(split.bill || 0) / Number(split.roommates) : 0; document.querySelector('#bill-input').value = split.bill || ''; document.querySelector('#roommates-input').value = split.roommates || ''; document.querySelector('#your-share-input').value = split.yourShare || ''; document.querySelector('#split-share').textContent = money(share); document.querySelector('#split-copy').textContent = split.bill ? `${money(split.bill)} divided between ${split.roommates} people.` : 'Enter a bill to see each person\'s share.'; }
function renderAnalytics() {
    const items = categoryTotals(); const list = document.querySelector('#top-category-list'); document.querySelector('#top-category-badge').textContent = items[0]?.category || 'No data yet';
    list.innerHTML = items.length ? items.slice(0, 5).map((item, index) => `<div class="money-item"><span class="money-item-icon">${categoryIcons[item.category] || '•'}</span><div><div class="money-item-name">${item.category}</div><div class="money-item-detail">${index === 0 ? 'Top spending category' : `${Math.round(item.total / currentMetrics().total * 100)}% of total expenses`}</div></div><strong class="money-item-amount">${money(item.total)}</strong></div>`).join('') : '<div class="empty-mini">Add expenses to see your spending patterns.</div>';
    const goal = Number(state.goal) || 0; const savings = Math.max(0, currentMetrics().savings); const percent = goal ? Math.min(100, savings / goal * 100) : 0; document.querySelector('#savings-percent').textContent = `${Math.round(percent)}%`; document.querySelector('#legend-savings').textContent = money(savings); document.querySelector('#legend-gap').textContent = money(Math.max(0, goal - savings)); document.querySelector('#savings-donut').style.background = `conic-gradient(var(--teal) ${percent * 3.6}deg, var(--mint) 0deg)`; drawCategoryChart(items);
}
function drawCategoryChart(items) { const canvas = document.querySelector('#category-chart'); const context = canvas.getContext('2d'); const width = canvas.clientWidth || 500; const height = 250; const ratio = window.devicePixelRatio || 1; canvas.width = width * ratio; canvas.height = height * ratio; context.scale(ratio, ratio); context.clearRect(0, 0, width, height); const colors = ['#0f766e', '#e77961', '#f3bb55', '#4a86c5', '#9b82c4']; const max = Math.max(...items.map(item => item.total), 1); const chartItems = items.slice(0, 6); const chartWidth = Math.max(40, width - 56); chartItems.forEach((item, index) => { const x = 26 + index * (chartWidth / Math.max(chartItems.length, 1)); const barWidth = Math.min(48, chartWidth / Math.max(chartItems.length, 1) - 15); const barHeight = item.total / max * 160; context.fillStyle = '#edf3f1'; context.roundRect(x, 22, barWidth, 160, 6); context.fill(); context.fillStyle = colors[index % colors.length]; context.roundRect(x, 182 - barHeight, barWidth, barHeight, 6); context.fill(); context.fillStyle = '#758386'; context.font = '10px DM Sans'; context.textAlign = 'center'; const label = item.category.length > 10 ? `${item.category.slice(0, 9)}…` : item.category; context.fillText(label, x + barWidth / 2, 207); context.fillStyle = '#172b3a'; context.font = '600 10px DM Sans'; context.fillText(money(item.total), x + barWidth / 2, 218); }); if (!chartItems.length) { context.fillStyle = '#8c9b9c'; context.font = '13px DM Sans'; context.textAlign = 'center'; context.fillText('Add expenses to bring your chart to life.', width / 2, 125); } }
function renderSummary() { const m = currentMetrics(); const items = categoryTotals(); document.querySelector('#summary-income').textContent = money(state.income); document.querySelector('#summary-expenses').textContent = money(m.total); document.querySelector('#summary-savings').textContent = money(m.savings); document.querySelector('#summary-goal').textContent = money(state.goal); document.querySelector('#summary-highest').textContent = items[0]?.category || '—'; document.querySelector('#summary-average').textContent = money(m.total / new Date().getDate()); document.querySelector('#summary-remaining').textContent = money(m.remaining); const previous = monthExpenses(previousMonth()); const previousFood = sum(previous.filter(item => item.category === (items[0]?.category || 'Food/Mess'))); const currentFood = items[0]?.total || 0; document.querySelector('#comparison-copy').textContent = previous.length ? `You spent ${money(Math.abs(currentFood - previousFood))} ${currentFood >= previousFood ? 'more' : 'less'} on ${items[0]?.category || 'your top category'} this month than last month.` : 'Add a few expenses to unlock your month-on-month comparison.'; }
function previousMonth() { const date = new Date(); date.setMonth(date.getMonth() - 1); return date.toISOString().slice(0, 7); }
function escapeHTML(value) { return String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function renderAll() { renderStats(); renderCategoryBars(); renderTable(); renderBudget(); renderRent(); renderSplit(); renderAnalytics(); renderSummary(); }
function openModal(expense = null) { editingId = expense?.id || null; document.querySelector('#modal-title').textContent = expense ? 'Edit an expense' : 'Add an expense'; document.querySelector('#expense-submit').textContent = expense ? 'Update expense' : 'Save expense'; document.querySelector('#expense-amount').value = expense?.amount || ''; document.querySelector('#expense-category').value = expense?.category || categories[0]; document.querySelector('#expense-date').value = expense?.date || todayISO; document.querySelector('#expense-description').value = expense?.description || ''; document.querySelector('#expense-modal').classList.add('open'); document.querySelector('#expense-modal').setAttribute('aria-hidden', 'false'); setTimeout(() => document.querySelector('#expense-amount').focus(), 50); }
function closeModal() { document.querySelector('#expense-modal').classList.remove('open'); document.querySelector('#expense-modal').setAttribute('aria-hidden', 'true'); editingId = null; }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2500); }
function setupNavigation() { document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', event => { event.preventDefault(); const target = link.dataset.section; document.querySelectorAll('.page-section').forEach(section => section.classList.toggle('active-section', section.dataset.page === target)); document.querySelectorAll('.nav-link').forEach(item => item.classList.toggle('active', item === link)); history.replaceState(null, '', `#${target}`); document.querySelector('#sidebar').classList.remove('open'); window.scrollTo({ top: 0, behavior: 'smooth' }); })); }

document.addEventListener('click', event => { const openButton = event.target.closest('[data-open-expense]'); if (openButton) openModal(); const editButton = event.target.closest('.edit-expense'); if (editButton) openModal(state.expenses.find(item => item.id === editButton.dataset.id)); const deleteButton = event.target.closest('.delete-expense'); if (deleteButton) { const expense = state.expenses.find(item => item.id === deleteButton.dataset.id); if (expense && confirm(`Delete “${expense.description}” from your expenses?`)) { state.expenses = state.expenses.filter(item => item.id !== expense.id); saveState(); renderAll(); showToast('Expense deleted'); } } });
document.querySelector('#expense-form').addEventListener('submit', event => { event.preventDefault(); const expense = { id: editingId || crypto.randomUUID(), amount: Number(document.querySelector('#expense-amount').value), category: document.querySelector('#expense-category').value, date: document.querySelector('#expense-date').value, description: document.querySelector('#expense-description').value.trim() }; if (editingId) state.expenses = state.expenses.map(item => item.id === editingId ? expense : item); else state.expenses.push(expense); saveState(); renderAll(); closeModal(); showToast(editingId ? 'Expense updated' : 'Expense added'); });
document.querySelector('#budget-form').addEventListener('submit', event => { event.preventDefault(); state.income = Number(document.querySelector('#income-input').value); state.goal = Number(document.querySelector('#goal-input').value); saveState(); renderAll(); showToast('Budget plan saved'); });
document.querySelector('#rent-form').addEventListener('submit', event => { event.preventDefault(); state.rent = { amount: Number(document.querySelector('#rent-input').value), dueDate: document.querySelector('#rent-due-input').value, paid: document.querySelector('#rent-paid-input').checked }; saveState(); renderAll(); showToast('Rent details saved'); });
document.querySelector('#split-form').addEventListener('submit', event => { event.preventDefault(); state.split = { bill: Number(document.querySelector('#bill-input').value), roommates: Number(document.querySelector('#roommates-input').value), yourShare: Number(document.querySelector('#your-share-input').value) }; saveState(); renderAll(); showToast('Split calculation saved'); });
document.querySelector('#modal-close').addEventListener('click', closeModal); document.querySelector('#expense-modal').addEventListener('click', event => { if (event.target.id === 'expense-modal') closeModal(); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); });
['#search-input', '#category-filter', '#date-filter'].forEach(selector => document.querySelector(selector).addEventListener('input', renderTable)); document.querySelector('#clear-filters').addEventListener('click', () => { document.querySelector('#search-input').value = ''; document.querySelector('#category-filter').value = 'all'; document.querySelector('#date-filter').value = ''; renderTable(); });
document.querySelector('#menu-button').addEventListener('click', () => document.querySelector('#sidebar').classList.add('open')); document.querySelector('#close-sidebar').addEventListener('click', () => document.querySelector('#sidebar').classList.remove('open')); window.addEventListener('resize', () => { if (document.querySelector('#analytics').classList.contains('active-section')) renderAnalytics(); });
const date = new Date(); document.querySelector('#current-date-label').textContent = date.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }).toUpperCase(); document.querySelector('#month-label').textContent = date.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }); populateCategories(); setupNavigation(); if (location.hash) { const link = document.querySelector(`[data-section="${location.hash.slice(1)}"]`); if (link) link.click(); } renderAll();
